/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InternalFrame;

import Entity.Category;
import ImplementInterface.categoryImpl;
import java.awt.Dimension;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author devtr
 */
public class QuanLyDanhMuc extends javax.swing.JInternalFrame {

    EditCat catinfo = new EditCat();
    categoryImpl catIplm = new categoryImpl();
    public ArrayList<Category> lstCategory;
    String strSetModel[] = new String[]{"ID Danh mục", "Tên", "Số TT"};
    DefaultTableModel dtmd = new DefaultTableModel(strSetModel, 0);

    public QuanLyDanhMuc() {

        initComponents();
        tbl_danh_muc.setDefaultEditor(Object.class, null);

        try {
            setdata();
        } catch (SQLException ex) {
            Logger.getLogger(QuanLyDanhMuc.class.getName()).log(Level.SEVERE, null, ex);
        }
        tbl_danh_muc.setModel(dtmd);
        JPopupMenu popupMenu = new JPopupMenu();
        JMenuItem menuItemAdd = new JMenuItem("Sửa");
        JMenuItem menuItemRemove = new JMenuItem("Xóa");
        popupMenu.add(menuItemAdd);
        popupMenu.add(menuItemRemove);
        tbl_danh_muc.setComponentPopupMenu(popupMenu);
    }

    public void setdata() throws SQLException {
        lstCategory = catIplm.getAllCat();
        dtmd.setRowCount(0);
        for (int i = 0; i < lstCategory.size(); i++) {
            Category get = lstCategory.get(i);
            Object data[] = {get.getCat_id(), get.getCat_name(), get.getSort()};
            dtmd.addRow(data);
        }
        tbl_danh_muc.setModel(dtmd);
    }

    private boolean checkOnly(JInternalFrame innerFrame) {
        JInternalFrame[] arrFrame = jDesktopPane_danh_muc.getAllFrames();
        for (JInternalFrame frame : arrFrame) {
            if (frame.getClass().getName() == innerFrame.getClass().getName()) {
                return true;
            }
        }
        return false;
    }

    public void centerJIF(JInternalFrame jif) {
        Dimension desktopSize = jDesktopPane_danh_muc.getSize();
        Dimension jInternalFrameSize = jif.getSize();
        int width = (desktopSize.width - jInternalFrameSize.width) / 2;
        int height = (desktopSize.height - jInternalFrameSize.height) / 2;
        jif.setLocation(width, height);
        jif.setVisible(true);
    }

    private void showFrame(JInternalFrame jintr) {
        if (!checkOnly(jintr)) {
            jDesktopPane_danh_muc.add(jintr);
            centerJIF(jintr);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane_danh_muc = new javax.swing.JDesktopPane();
        jPanel_danh_muc = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_danh_muc = new javax.swing.JTable();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel_danh_muc.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh Mục", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        tbl_danh_muc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_danh_muc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_danh_mucMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_danh_muc);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jButton2.setText("Thêm Danh Mục");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Tìm kiếm");

        javax.swing.GroupLayout jPanel_danh_mucLayout = new javax.swing.GroupLayout(jPanel_danh_muc);
        jPanel_danh_muc.setLayout(jPanel_danh_mucLayout);
        jPanel_danh_mucLayout.setHorizontalGroup(
            jPanel_danh_mucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_danh_mucLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_danh_mucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_danh_mucLayout.createSequentialGroup()
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel_danh_mucLayout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE)
        );
        jPanel_danh_mucLayout.setVerticalGroup(
            jPanel_danh_mucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_danh_mucLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel_danh_mucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jDesktopPane_danh_muc.setLayer(jPanel_danh_muc, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane_danh_mucLayout = new javax.swing.GroupLayout(jDesktopPane_danh_muc);
        jDesktopPane_danh_muc.setLayout(jDesktopPane_danh_mucLayout);
        jDesktopPane_danh_mucLayout.setHorizontalGroup(
            jDesktopPane_danh_mucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_danh_muc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDesktopPane_danh_mucLayout.setVerticalGroup(
            jDesktopPane_danh_mucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_danh_muc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane_danh_muc)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane_danh_muc)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JInternalFrame add = new AddNewCat();
        showFrame(add);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void tbl_danh_mucMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_danh_mucMouseClicked
        String cat_id = tbl_danh_muc.getValueAt(tbl_danh_muc.getSelectedRow(), 0).toString();
//       JInternalFrame add = new AddNewCat();
//       showFrame(add);
        for (int i = 0; i < lstCategory.size(); i++) {
            Category get = lstCategory.get(i);
            if (get.getCat_id() == Integer.valueOf(cat_id)) {
                System.out.println("click cat_id=" + cat_id);
                jDesktopPane_danh_muc.add(catinfo);
                catinfo.setVisible(true);

                catinfo.tf_cat_name.setText(get.getCat_name());
                catinfo.tf_cat_sort.setText(String.valueOf(get.getSort()));
                catinfo.lb_cat_id.setText(String.valueOf(get.getCat_id()));

            }

        }
    }//GEN-LAST:event_tbl_danh_mucMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JDesktopPane jDesktopPane_danh_muc;
    private javax.swing.JPanel jPanel_danh_muc;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTable tbl_danh_muc;
    // End of variables declaration//GEN-END:variables
}
